# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - selenium

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail

    tensorflow.gpu:
#        image: tensorflow/tensorflow:2.9.2-gpu-jupyter
        image: xcxlab/jupyterlab-gpu:1.0.0b
        container_name: 'xcxlab_jupyterlab-GPU'
        ports:
            - 8888:8888
        volumes:
            - ${JUPYTER_CONFIG}:/root/.jupyter/
            - ${JUPYTER_STARTUP}:/root/.ipython/profile_default/startup/
        links:
            - orthanc
        networks:
            - backend
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    flask:
        image: easl/flask:1.0
        ports:
            - 5000:5000
        volumes:
            - ${FLASK_BACKEND}:/root/
        links:
            - orthanc
        networks:
            - backend


    rstudio:
        image: 'xcxlab/rstudio' # Dockerfile located in xcxlab/dockerfiles/rstudio
        container_name: 'xcxlab_rstudio'
        ports:
            - 8787:8787
        environment:
            - DISABLE_AUTH=true
        volumes:
            - ${RSTUDIO_SERVER_CONFIG}:/etc/rstudio/
            - ${RSTUDIO_SHINY_APP_DIRECTORY}:/srv/shiny-server/
            - ${RSTUDIO_LIBRARY_PATH}:/usr/local/lib/R/site-library/
            - ${RSTUDIO_HOME}:/home/rstudio/interfaces/

    shiny.server:
        image: 'xcxlab/shiny' # Dockerfile located in xcxlab/dockerfiles/shiny
        container_name: 'xcxlab_shiny'
        environment:
            - DISABLE_AUTH=true
        ports:
            - 3838:3838
        volumes:
            - ${RSTUDIO_SHINY_APP_DIRECTORY}:/srv/shiny-server/
            - ${RSTUDIO_LIBRARY_PATH}:/usr/local/lib/R/site-library/

    nginx:
        image: nginx:1.7.7
        container_name: nginx
        restart: always
        networks:
            - frontend
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - sampledata:/sampledata
            - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
            - ${NGINX_SSL_CERT:-./ssl/ssl_dev.crt}:/etc/ssl/SSL.crt:ro  # SSL development certificate
            - ${NGINX_SSL_KEY:-./ssl/ssl_dev.key}:/etc/ssl/SSL.key:ro   # SSL development key
#            - matomo:/var/www/html:ro
#            - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro

    viewer:
        image: ohif/viewer:v1.x
        container_name: viewer
        depends_on:
            - mongo
            - orthanc
        restart: always
        networks:
            - frontend
            - backend
        ports:
          - 3000:3000
        links:
            - mongo
        environment:
            - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/ohif}
        volumes:
            - ${VIEWER_CONFIG:-./vendor/OHIF/config/viewer.json}:/app/app.json:ro

    mongo:
        image: mongo:4.0.14
        container_name: mongo
        networks:
            - backend
        #    ports:
        #      - ${MONGO_PORT:-27017}:27017
        volumes:
            - ${MONGO_DATA:-./mongo_data}:/data/db

    orthanc:
        image: jodogne/orthanc-plugins:1.5.8
        container_name: orthanc
        depends_on:
            - postgres
        restart: always
        networks:
            - frontend
            - backend
        ports:
          - ${ORTHANC_DICOM_PORT:-4242}:4242
          - ${ORTHANC_HTTP_PORT:-8042}:8042
        volumes:
            - sampledata:/sampledata
            - ${ORTHANC_DB:-./orthanc_db}:/var/lib/orthanc/db
            - ${ORTHANC_CONFIG:-./config/orthanc.json}:/etc/orthanc/orthanc.json:ro
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
            - PGDATA=${PGDATA:-/var/lib/postgresql/data}
            - POSTGRES_DB=orthanc
        expose:
            - 8042

    postgres:
        image: postgres:12.1
        container_name: postgres
        networks:
            - backend
        ports:
          - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - ${POSTGRES_DATA_MNT:-/pg_data/data}:${PGDATA:-/var/lib/postgresql/data}
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
            - PGDATA=${PGDATA:-/var/lib/postgresql/data}
            - POSTGRES_DB=orthanc

    nginx-matomo:
        image: nginx:alpine
        container_name: nginx-matomo
        restart: always
        volumes:
            - matomo:/var/www/html:ro
            # see https://github.com/matomo-org/matomo-nginx
            - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8081:80

    matomo:
        image: matomo:fpm-alpine
        container_name: matomo
        restart: always
        links:
            -   mysql
        volumes:
            -   matomo:/var/www/html
        environment:
            - MATOMO_DATABASE_HOST=mysql
            - PHP_MEMORY_LIMIT=2048M
        env_file:
            -   .env


networks:
    sail:
        driver: bridge
    frontend:
    backend:

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sampledata:
    mysql:
    matomo:

