# syntax=docker/dockerfile:1
FROM rocker/rstudio:latest
RUN apt-get update && apt-get install -y \
    libgsl-dev \
    libz-dev \
    libbz2-dev \
    liblzma-dev \
    libgeos-dev \
    libxml2-dev \
    libglpk-dev \
    libxt6 \
    libmagick++-dev